packages/vue/__tests__/unit/searchProvider.spec.js
packages/vue/src/providers/SearchProvider.js

**Ticket**
[LS-1213](https://nacelle.atlassian.net/browse/LS-1213)
**Changes**
conform search provider + testing to warp2 schema
**Testing**
- `git checkout LS-1213--warp2-search-provider`
- `cd packages/vue`
- `npm run test -- searchProvider.spec.js`

fix: conform search provider to warp2 schema

---

packages/vue/__tests__/unit/productProvider.spec.js
packages/vue/mocks/product.js
packages/vue/src/providers/ProductProvider.js

**Ticket**
https://nacelle.atlassian.net/browse/LS-1212
**Changes**
make product provider, tests and mock compatible with warp2
**Testing**
- `git checkout LS-1213--warp2-product-provider`
- `cd packages/vue`
- `npm run test -- productProvider.spec.js`

fix: make product provider compatible with warp2

---

packages/shopify-checkout/src/utils/metafieldsToCustomAttributes.ts

**What This PR Does**
- ensures shopifyCheckout package only passes through `checkoutAttributes` with values that are strings
**Testing**
- `npm run test:ci`
**Notes**
- the `Attribute` and `Metafield` types were left unchanged intentionally so that typescript users would still get type errors if the values passed weren't strings.  The caveat is that there is no test against passing in other values.  Another approach where types are updated can be seen on this branch: 
https://github.com/getnacelle/nacelle-js/tree/LS-1306--null-checkout-attrs

chore: adds typecheck for string

---

starters/next/pages/_app.js

Story [[LS-1490](https://nacelle.atlassian.net/browse/LS-1490)] 
Renames `NextStarter` to `AppContainer` and adds a comment about Next's custom app feature.
1. Checkout this branch.
2. `npm run bootstrap`
2. `cd starters/next`
3. `npm run dev`

refactor(starters/next): rename custom app

---

starters/gatsby/gatsby-browser.js

**What This PR Does**
- removes `Layout` component from `wrapRootElement` so it doesn't render twice

fix(starters/gatsby): remove duplicate layout component

---

packages/shopify-checkout/src/graphql/fragments/index.ts
packages/shopify-checkout/src/graphql/mutations/index.ts
packages/shopify-checkout/src/graphql/queries/index.ts

**What this PR does**
- ticket: [LS-1547](https://nacelle.atlassian.net/browse/LS-1547)
- adds new gql fragments for `lineItem`, `discountApplication`, `checkout`, `userError`
- uses fragments to queries and mutations
**Notes**
I think this is what was intended by ticket.  If not happy to make updates.  This ticket was simply to get the fragments in repo.  It is not intended to be the full update.  That is handled by: [LS-1548](https://nacelle.atlassian.net/browse/LS-1548)

chore: new graphql fragments

---

packages/gatsby-source-nacelle/src/type-defs/index.js
packages/gatsby-source-nacelle/src/utils/replaceKey.js

Fixes [[LS-1583](https://nacelle.atlassian.net/browse/LS-1583)] 
- Renames `fields` to `remoteFields` for `CollectionContent`, `ProductContent`, and `VariantContent` types.
- Updates `replaceKey` to recursively search for keys.
Easiest way to test would probably be with the Gatsby Starter.
- In `starters/gatsby` add a `.env` file with the following (This space has content fields set up for Product, Variant, and Collection content. However, do to an [issue](https://nacelle.atlassian.net/browse/ENG-4140), this will be returned as stringified JSON): 
```
GATSBY_NACELLE_STOREFRONT_TOKEN=979f5597-6b7d-46df-8429-b8ac474eb9d2
GATSBY_NACELLE_STOREFRONT_ENDPOINT=https://storefront.api.development.nacelle.com/graphql/v1/spaces/ckyaffo3m1654353oyzztyzelhh
GATSBY_NACELLE_STOREFRONT_LOCALE="en-US" …
```

fix(gatsby-source-nacelle): replace field key

---

packages/shopify-checkout/__tests__/mocks/index.ts
packages/shopify-checkout/src/client/actions/discount.spec.ts
packages/shopify-checkout/src/client/actions/findCheckout.spec.ts
packages/shopify-checkout/src/client/actions/putCheckout.spec.ts
packages/shopify-checkout/src/client/client-dom.spec.ts
packages/shopify-checkout/src/utils/isVerifiedCheckoutId.spec.ts
packages/shopify-checkout/src/utils/isVerifiedCheckoutId.ts

Fixes [ENG-4354](https://nacelle.atlassian.net/browse/ENG-4354)
> @nacelle/shopify-checkout is erroneously reporting checkout ids as invalid
Our validation of Shopify checkout IDs in `packages/shopify-checkout/src/utils/isVerifiedCheckoutId.ts` was not accounting for an aspect of Base64 encoding.
Notice how in the following example, when the Checkout ID starts with a letter, the Base64-encoded string has a trailing `1dC9`, whereas the absence of a Checkout ID or a Checkout ID that starts with a number has a trailing `1dC8`:
Because we used `'Z2lkOi8vc2hvcGlmeS9DaGVja291dC8'` as a comparison string, the `isVerifiedCheckoutId` utility was incorrectly returning `false` when a Checkout ID began with a letter.
This PR changes `isVerifiedCheckoutId`'s comparison string to …

fix(shopify-checkout): accept checkout IDs that start with letter

---

packages/gatsby-source-nacelle/gatsby-node.js
packages/gatsby-source-nacelle/src/queries/index.js
packages/gatsby-source-nacelle/src/queries/product-collections-entries.js
packages/gatsby-source-nacelle/src/queries/product-collections.js
packages/gatsby-source-nacelle/src/utils/index.js
packages/gatsby-source-nacelle/src/utils/paginateEntries.js
packages/gatsby-source-nacelle/src/utils/paginateQuery.js

Fixes [[ENG-4723](https://nacelle.atlassian.net/browse/ENG-4723)] 
- Collection queries were not returning all products assigned to collections.
- Replaces the use of the `productCollections` SDK method with a custom query using the `query` SDK method.
- Requests more collections if there are more to be fetched.
- Requests more collection products if there are more to be fetched.
- Run `npm run bootstrap` in the root directory.
- Update the `.env` file in `starters/gatsby` OR use your own Gatsby project (will require `npm link`ing the `gatsby-source-nacelle` package).
- To test with project that experienced this issue, see the ticket above for credentials, otherwise provide one of our reference stores.

feat(gatsby-source-nacelle): adds pagination to product collections query

---

reference-stores/nuxt/components/search/SearchInput.vue

**What This PR Does**
Ensures the search autocomplete dropdown closes on enter keypress.  
**How To Test**
Spin up this branch.  Enter some search terms in search input and hit enter.  The autocomplete dropdown should close

chore: close search autocomplete on enter

---

packages/gatsby-source-nacelle/src/source-nodes/index.js

Fixes [ENG-5388](https://nacelle.atlassian.net/browse/ENG-5388) - Fixes the issue in Gatsby Source Nacelle where empty Nacelle Node types were being logged as cached. 
- If no nodes were added and the content is empty, logs that no nodes were created.
This is an abridged set of instructions adapted from #138
1. Checkout `mdarrik/ENG-5388-console-statements-mistakenly-claim-cached-nodes`
2. navigate to an existing gatsby repo using `gatsby-source-nacelle` or this repo's starter with a `.env` file that points to a space with empty types (navigation or contentCollection are commonly empty)
1. For this repo's starter, make sure you run `npm run bootstrap` at the root of this repo first to install dependencies
3. Run a clean `npm run clean`
4. Run a build `npm run build` - should see a log …

fix: log empty node types instead of claiming they're cached

---

.github/workflows/pr-health-checks.yml

Adds a conditional to `pr-health-checks` to not run if the PR was opened by dependabot.  This should fix the failing workflows on dependabot PRs
This line of code has been added to a failing [dependabot PR](https://github.com/getnacelle/nacelle-js/pull/130).  The `pr-health-checks` job is no longer running.  You can ignore the other failing job, it is resolved in future PRs.

chore: dependabot build fix

---

packages/shopify-checkout/src/client/actions/checkoutCreate.ts
packages/shopify-checkout/src/client/actions/putCheckout.spec.ts

Fixes [ENG-5496](https://nacelle.atlassian.net/browse/ENG-5496) - bug where `checkoutCreate`'s checkoutUserErrors were not getting passed to the error handling. This caused the error message to not include why the error was thrown. 
1. Fixes the bug where `checkoutUserErrors` weren't getting passed to the handleShopifyError logic in `checkoutCreate`
2. Adds tests to put checkout for handling a generic `errors` response, and a generic mutation-specific error (which is a child of `data` in the response) for each of the possible mutations triggered by `putCheckout`. 
1. Run `npm run test:ci` in the `packages/shopify-checkout` folder. All tests should pass.

fix(shopify-checkout): correctly include checkoutUserErrors in error handling on checkoutCreate

---

packages/shopify-checkout/README.md
packages/shopify-checkout/__tests__/mocks/index.ts
packages/shopify-checkout/package-lock.json
packages/shopify-checkout/src/client/actions/index.ts
packages/shopify-checkout/src/client/actions/queryCheckout.spec.ts
packages/shopify-checkout/src/client/actions/queryCheckout.ts
packages/shopify-checkout/src/client/client-dom.spec.ts
packages/shopify-checkout/src/client/index.ts
packages/shopify-checkout/src/utils/createGqlClient.ts

Fixes [[ENG-6125](https://nacelle.atlassian.net/browse/ENG-6125)] 
- add Shopify checkout custom query method
- update Shopify API version to 2022-07
🖥 [Local development instructions](#link-to-repo-readme)
🗒 [General testing guidelines](#link-to-testing-guidelines)
📄 [Changelog guidelines](#link-to-changelog-guidelines)
- `npm run test` everything should pass
For end to end testing
- there is a branch of the [shopify-checkout-react-discounts-testing](https://github.com/getnacelle/shopify-checkout-react-discounts-testing/tree/ENG-6125--shopify-custom-query) that is made to test this feature
- for me `npm run build && npm run preview` worked better than `npm run dev` for some reason
- click "Process Checkout" and look at the request in the network tab, make sure that the endpoint uses the …

feat: shopify checkout custom query

---

examples/nuxt-3/README.md
examples/nuxt-3/app.vue
examples/nuxt-3/components/ProductCard.vue
examples/nuxt-3/composables/cart/index.ts
examples/nuxt-3/nuxt.config.ts
examples/nuxt-3/pages/collections/[handle].vue
examples/nuxt-3/pages/products/[handle].vue
examples/nuxt-3/queries/index.js

To support #205.
Currently, it doesn't seem possible to run Nuxt 2 and Nuxt 3 linting setups in the same monorepo. To do that, [Volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar) would need to provide an option to define sub-projects that it runs in, [as Vetur does](https://vuejs.github.io/vetur/guide/setup.html#advanced).
With that in mind, it's challenging to run ESLint on the `examples/nuxt-3` project introduced in #205. We can do this locally, though, using an ESLint config setup [that closely mirrors this](https://github.com/nuxt/framework/discussions/2815#discussioncomment-2050408).
This PR fixes some issues highlighted by:
1. `'eslint:recommended'`
2. `'plugin:vue/vue3-essential'`
3. `'plugin:@typescript-eslint/recommended'`
4. …

fix: linting

---

packages/shopify-cart/src/utils/index.ts
packages/shopify-cart/src/utils/sanitizeFragment.spec.ts
packages/shopify-cart/src/utils/sanitizeFragment.ts

Addresses [ENG-6849](https://nacelle.atlassian.net/browse/ENG-6849)
> Sanitize user-supplied fragments to ensure consistent fragment names and types
This PR adds a new `sanitizeFragment` utility that ensures that user-supplied GraphQL fragments have the expected fragment name and GraphQL type. This will reduce opportunities for user-supplied GraphQL fragments to result in errors due to not adhering to our fragment naming conventions or using an unexpected GraphQL type for a given fragment.
1. Check out the `ENG-6849-sanitize-user-supplied-fragments` branch.
2. `npm run bootstrap` from the monorepo root, as needed.
3. `cd packages/shopify-cart`
4. `npm run test:ci -- utils/sanitizeFragment` - tests should pass with 100% coverage:

feat: sanitize user-supplied GraphQL fragments

---

packages/shopify-cart/README.md
packages/shopify-cart/__tests__/mocks/index.ts
packages/shopify-cart/codegen.yml
packages/shopify-cart/src/types/shopify.type.ts
packages/shopify-cart/src/utils/createGqlClient.ts

Addresses [ENG-6848](https://nacelle.atlassian.net/browse/ENG-6848)
> Update Shopify API to `2022-07` & run `codegen`
This PR updates all instances of the Shopify API from `2022-04` to `2022-07`.  All types are generated from the newer API version and mocks are updated.
1. Check out the `ENG-6848/update-shopify-api` branch.
2. `npm run bootstrap` from the monorepo root, as needed.
3. `cd packages/shopify-cart`
4. `npm run test:ci` - tests should pass with 100% coverage:
Using the `thinx-test` vite project confirm the following mutations work.

chore: update API & types

---

.changeset/lucky-monkeys-glow.md
packages/shopify-cart/README.md
packages/shopify-cart/src/client/actions/cartCreate.spec.ts
packages/shopify-cart/src/client/actions/cartCreate.ts

Addresses [ENG-6892](https://nacelle.atlassian.net/browse/ENG-6892)
> Allow `cartCreate` to work with no params - `cartCreate()`
This PR ensures empty params can be passed to `cartCreate` mutation.  Adds test to cover scenario.
1. Check out the `ENG-6892/cart-create-empty-params` branch.
2. `npm run bootstrap` from the monorepo root, as needed.
3. `cd packages/shopify-cart`
4. `npm run test cartCreate` - tests should pass with 100% coverage:
Using the `thinx-test` vite project confirmed that `cartCreate` can now be called with no params

fix: cart create empty params

---

.changeset/tidy-dryers-decide.md
packages/shopify-cart/package.json
packages/shopify-cart/vite.config.ts

Addresses [ENG-6979](https://nacelle.atlassian.net/browse/ENG-6979) - Updates vite config for shopify-cart to ship mjs files for esm. This allows node packages to use native esm. 
1. Replaces the file mapping in the `vite.config.js` with just the file name. This causes Vite to ship `mjs` files for `es` targets.
2. Removes the rollup section
3. Sets the target to es2018. Should support most of our users without transpilation, and sites who need older targets can transpile. 
4. Removes the minify key so Vite can use esbuild by default. 
1. Checkout thisbranch locally `mdarrik/shopify-cart/ENG-6979-update-vite-config-for-esm`
2. Run a build with `npm run build`, should see dist files for `nacelle-shopify-cart.mjs`, `nacelle-shopify-cart.iife.js`  & `nacelle-shopify-cart.umd.js`.
3. You …

feat: cleans up vite config to ship mjs

---

packages/shopify-cart/src/client/actions/cartCreate.ts
packages/shopify-cart/src/client/actions/cartLinesAdd.ts
packages/shopify-cart/src/client/actions/cartLinesUpdate.ts
packages/shopify-cart/src/utils/transformNacelleLineItemToShopifyLineItem.ts

To support #227.
Refactors `packages/shopify-cart/src/utils/transformNacelleLineItemToShopifyLineItem.ts` with [conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html). This allows us to eliminate type assertions where `transformNacelleLineItemToShopifyLineItem` is called, which in turn allows us to simplify some of the `packages/shopify-cart/src/client/actions`.
The idea with the conditional types is that by checking to see if the input to `transformNacelleLineItemToShopifyLineItem` is `NacelleCartLineItemUpdateInput` or not (when it's not, it's `NacelleCartInput`), we can have TypeScript automatically know if the `transformNacelleLineItemToShopifyLineItem` return value is `CartLineInput` or `CartLineUpdateInput`.
For example (keeping in mind that the …

refactor: conditional types to simplify actions

---

packages/shopify-cart/package.json
packages/shopify-cart/src/index.ts
packages/shopify-cart/vite.config.ts

Fixes [ENG-6992](https://nacelle.atlassian.net/browse/ENG-6992) - Makes all public types exportable from the package base. This helps keep our public type api clean, and reduces the chances that removing/renaming internal types breaks user code.  
- Creates a new entry point at `src/index.ts`. This entry point re-exports everything from `src/client.ts` and all other public types.
- Updates vite to use this new entry point
- Updates the `types` key in `package.json` to point to the `dist/types/index.d.ts` file that corresponds to this new entry point. This makes all public types importable from `@nacelle/shopify-cart` 
1. Checkout this branch `mdarrik/shopify-cart/ENG-6992-export-all-public-types-from-package-root`
2. Run a build `npm run build` - should build successfully
3. In a ts …

feat: use src/index.ts as new entry file

---

packages/shopify-cart/README.md

Addresses [ENG-7063](https://nacelle.atlassian.net/browse/ENG-7063)
> Add `customFragments` to "Initializing the client" docs in the README
In the "Initializing the client" docs, `customFragments` were missing from the list of initialization options.
- Adds `customFragments` to the list of initialization options.
- Corrects the type of `fetchClient` (was `object`, should be `function`).
Here's what the README looks like now:

docs: add `customFragments` to client init options

---

packages/shopify-cart/src/client/client-dom.spec.ts
packages/shopify-cart/src/client/index.ts
packages/shopify-cart/src/graphql/fragments/cart.ts

Fixes [ENG-7163](https://nacelle.atlassian.net/browse/ENG-7163)
> Merchandise fragment cannot be provided in `customFragments`
There were omissions from #229 that resulted in `MERCHANDISE` custom fragments not being applied.
1. Ensures `customFragments.MERCHANDISE` is used in `src/graphql/fragments/cart.ts`.
2. Fixes types and allows them to be generated with [`JayFong.generate-index`](https://marketplace.visualstudio.com/items?itemName=JayFong.generate-index) in the future, if we add more fragments.
3. Adds more unit tests to guard against future regressions.
1. Check out the `ENG-7163-fix-merchandise-custom-fragment` branch.
2. Navigate to `packages/shopify-cart`
4. `npm run build` - it should build without errors.
5. `npm run codegen` - there should be no uncommitted changes.
6. `npm …

fix: allow merchandise fragment to be supplied

---

.changeset/cold-oranges-study.md
.changeset/gorgeous-gifts-sip.md
.changeset/lucky-monkeys-glow.md
.changeset/old-monkeys-reply.md
.changeset/pre.json
.changeset/soft-terms-visit.md
.changeset/tame-dryers-visit.md
.changeset/tidy-dryers-decide.md
.changeset/tricky-melons-fry.md
.github/workflows/release.yml
examples/nuxt-3/package.json
reference-stores/next/package.json

**NOTE:** This PR is a draft PR until we're ready to release the 1.0.0-beta. 
Addresses [ENG-7143](https://nacelle.atlassian.net/browse/ENG-7143) - sets up changesets and the gh actions for releasing the Shopify Cart 1.0.0-beta 
1. Adds missing "version" key to `examples/nuxt-3/package.json`. This fixes an error preventing `changeset version` from working in pre-release mode
2. Updates the "name" key in `reference-store/next/package.json` to be `next-reference-store` instead of `next` since this confused changesets into thinking all NextJS repos were using the reference store as a dependency.
3. Updates any changesets for breaking changes to be tagged as `major` instead of `minor` so that changeset knows to up the version to `1.0.0-beta` instead of `0.X.X-beta`
4. Enters changeset's …

chore: Configure Changesets to publish Shopify Cart Beta

---

packages/shopify-cart/src/client/actions/cart.ts
packages/shopify-cart/src/client/actions/cartAttributesUpdate.ts
packages/shopify-cart/src/client/actions/cartBuyerIdentityUpdate.ts
packages/shopify-cart/src/client/actions/cartCreate.ts
packages/shopify-cart/src/client/actions/cartDiscountCodesUpdate.ts
packages/shopify-cart/src/client/actions/cartLinesAdd.ts
packages/shopify-cart/src/client/actions/cartLinesRemove.ts
packages/shopify-cart/src/client/actions/cartLinesUpdate.ts
packages/shopify-cart/src/client/actions/cartNoteUpdate.ts
packages/shopify-cart/src/client/index.ts
packages/shopify-cart/src/graphql/fragments/cart.ts
packages/shopify-cart/src/graphql/fragments/index.ts
packages/shopify-cart/src/graphql/mutations/cartAttributesUpdate.ts
packages/shopify-cart/src/graphql/mutations/cartBuyerIdentityUpdate.ts
packages/shopify-cart/src/graphql/mutations/cartCreate.ts
packages/shopify-cart/src/graphql/mutations/cartDiscountCodesUpdate.ts
packages/shopify-cart/src/graphql/mutations/cartLineAdd.ts
packages/shopify-cart/src/graphql/mutations/cartLineRemove.ts
packages/shopify-cart/src/graphql/mutations/cartLineUpdate.ts
packages/shopify-cart/src/graphql/mutations/cartNoteUpdate.ts
packages/shopify-cart/src/graphql/mutations/index.ts
packages/shopify-cart/src/graphql/queries/cart.ts
packages/shopify-cart/src/index.ts
packages/shopify-cart/src/types/shopify.type.ts
packages/shopify-cart/src/utils/depaginateLines.ts
packages/shopify-cart/src/utils/sanitizeFragments.spec.ts
packages/shopify-cart/src/utils/sanitizeFragments.ts

Addresses [ENG-7164](https://nacelle.atlassian.net/browse/ENG-7164)
> Throw when a fragment in `customFragments` doesn't use a valid fragment key
It was easy for misspelled or otherwise invalid `customFragments` to be supplied to the cart client. Those fragments were being quietly ignored. To surface issues to the merchant developer, we should have invalid `customFragments` fail loudly with a thrown error.
1. If any of the supplied `customFragments` don't use the expected fragment keys (such as `MERCHANDISE` or `EXTEND_CART_LINE`), an error is thrown.
2. Updates unit tests to validate that an error is thrown when invalid `customFragments` are supplied.
3. Simplifies the typings, such that the `CustomFragments` type is used universally wherever `customFragments` are used.
4. Updates the …

feat!: error when provided invalid fragment key

---

packages/shopify-cart/README.md

Fixes [ENG-7057](https://nacelle.atlassian.net/browse/ENG-7057) 
- clarify line params docs for `cartCreate`, `cartLinesAdd`, and `cartLinesUpdate`
Should we update the ways `cartLinesRemove` works as well? It is making use of the Shopify cart line ID at the moment.

chore:  clarify line params docs

---

.changeset/old-colts-attend.md
packages/shopify-cart/README.md
packages/shopify-cart/src/client/client-dom.spec.ts
packages/shopify-cart/src/client/index.ts

Addresses [ENG-7167](https://nacelle.atlassian.net/browse/ENG-7167) - Adds a setConfig and getConfig to the cart client. 
- Adds a getConfig method that returns the string options passed to `createCartClient`
- Adds a `setConfig` method to allow you to update the `language` and `countryCode`
- Checkout this branch `mdarrik/shopify-cart/ENG-7167-add-setConfig-properties-to-cart` 
- Run `npm run test:ci` - all tests should pass
- Run `npm run build` - should build successfully
- To test in a local repo - use `npm link` and try calling `getConfig` to see the options used in the cart, and test updating the language/country with `setConfig`

feat: adds get/set config functions

---

packages/shopify-cart/README.md

Addresses [ENG-7058](https://nacelle.atlassian.net/browse/ENG-7058)
> Document the `cart` format in README
More precisely describes the `cart` data and how it differs from Shopify's `cart` schema.

docs: describe Nacelle & Shopify cart differences

---

packages/shopify-cart/package.json
packages/shopify-cart/tsconfig.production.json

Addresses [ENG-7255](https://nacelle.atlassian.net/browse/ENG-7255)
> Configure @nacelle/shopify-cart typescript for production
Previously, unit tests had type errors because `src/**/*.spec.ts` and `__tests__` were excluded from TypeScript compilation:
This PR doesn't exclude `src/**/*.spec.ts` and `__tests__` in development, and only excludes them in production (`npm run build`). We accomplish this by creating a separate `tsconfig` and using it in `npm run build`.
1. Check out the `ENG-7255-configure-ts-for-production` branch.
2. Navigate to `packages/shopify-cart`.
3. `npm run build` - there should be no build errors.
4. Open a unit test file. There should be no type errors:

chore: configure tsconfig for production

---

.github/workflows/release.yml
examples/nuxt-3/package.json
packages/sanity-plugin-nacelle-input/README.md

This PR:
1. Updates a npm script name to match: https://github.com/getnacelle/nacelle-js/blob/e2785872175c8ec84957def0af07e2d33d284faf/examples/nuxt-3/package.json#L10
2. Makes a small change to a `packages/*` project in order to trigger the `Release` workflow.
3. [Enables](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) the `Release` workflow to be manually triggered from https://github.com/getnacelle/nacelle-js/actions/workflows/release.yml in the future.

chore: update script name to match feature branch

---

.changeset/twenty-ducks-vanish.md

#281 is erroneously trying to publish `@nacelle/sanity-plugin-nacelle-input`. By removing this changeset (which was removed from `main` in #271), we can stop `changesets/bot` from trying to publish a `@beta` version of `@nacelle/sanity-plugin-nacelle-input`.

chore: prevent erroneous package publish

---

.changeset/tidy-carrots-train.md
packages/gatsby-source-nacelle/package-lock.json
packages/gatsby-source-nacelle/package.json
packages/gatsby-source-nacelle/src/utils/isUnresolvableNacelleReference.js
packages/gatsby-source-nacelle/src/utils/linkNestedContentReferences.js

Fixes [ENG-6791](https://nacelle.atlassian.net/browse/ENG-6791) - fixes the `gatsby-source-nacelle` plugin for Content Improvement spaces by handling NacelleReferences & image assets.  
1. Adds logic to skip making Node references for entries with `type: asset` that have an `nacelleEntryId`. This is because post-CIB, images have a `nacelleEntryId` key, but are not queryable as top-level entries. This creates issues for the existing node linking logic since the referenced nodes don't exist. 
2. Removes NacelleReferences that are not resolvable from the Node tree if they are references that cannot be found by Nacelle's Hail Frequency. Since they're not findable, they won't exist in the node tree & prevents sites from building. 
1. Checkout this branch - …

fix(gatsby): fix breaking changes around CIB

---

.changeset/ten-pears-jam.md
packages/shopify-checkout/src/graphql/fragments/index.ts

Fixes [ENG-7932](https://nacelle.atlassian.net/browse/ENG-7932)
> Completed checkouts are being returned as completed: false
Our `Checkout_checkout on Checkout` fragment was missing an expected top-level field, `completedAt`:
https://github.com/getnacelle/nacelle-js/blob/fe526713227e275a575c1a406ec105a64ca9e544/packages/shopify-checkout/src/graphql/fragments/index.ts#L48-L69
Because our package code expects `completedAt`, this was causing the `completed` value in the `ShopifyCheckout` payload to be `false` when the checkout had in fact been completed.
This PR adds `completedAt` to the checkout fragment.
First, the basics:
1. Check out the `ENG-7932-completed-checkouts-are-being-returned-as-incomplete` branch.
2. `npm run bootstrap` from the monorepo root.
3. Navigate to …

fix: add missing field to checkout fragment

---

.changeset/tricky-scissors-flash.md
packages/shopify-checkout/README.md
packages/shopify-checkout/__tests__/mocks/index.ts
packages/shopify-checkout/src/client/actions/applyDiscount.ts
packages/shopify-checkout/src/client/actions/discount.spec.ts
packages/shopify-checkout/src/client/actions/findCheckout.spec.ts
packages/shopify-checkout/src/client/actions/putCheckout.spec.ts
packages/shopify-checkout/src/client/actions/putCheckout.ts
packages/shopify-checkout/src/client/actions/removeDiscount.ts
packages/shopify-checkout/src/client/client-dom.spec.ts
packages/shopify-checkout/src/utils/isVerifiedCheckoutId.spec.ts
packages/shopify-checkout/src/utils/isVerifiedCheckoutId.ts

Fixes [ENG-7943](https://nacelle.atlassian.net/browse/ENG-7943)
> Shopify checkout ID verification doesn't account for plaintext IDs
Shopify [made a change](https://shopify.dev/changelog/improvements-and-changes-coming-to-the-storefront-api) to the Shopify Storefront API that creates a bug in `@nacelle/shopify-checkout`. Previously, Shopify returned base64-encoded global IDs for all nodes (including Checkout nodes).
[Shopify’s description of this change includes](https://shopify.dev/changelog/changes-to-storefront-api-object-ids):
> …when requesting the unstable, 2022-04 release candidate, or future versions of the Storefront API, the object IDs returned will no longer be Base64 encoded.
This change breaks [@nacelle/shopify-checkout's `isVerifiedCheckoutId` utility …

fix: allow plaintext Shopify global IDs

---

.changeset/pre.json
.changeset/spindrifts-taste-tasty.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/workflows/release.yml
packages/shopify-cart/.env.example
packages/shopify-cart/tsconfig.production.json
reference-stores/gatsby/package.json
reference-stores/next/package.json
reference-stores/nuxt/package.json
starters/gatsby/package.json
starters/next/package.json
starters/nuxt/package.json

Addresses [ENG-8014](https://nacelle.atlassian.net/browse/ENG-8014) / supports #278.
- Exits [changesets prerelease mode](https://github.com/changesets/changesets/blob/main/docs/prereleases.md).
- Removes [`ENG-6843/shopify-cart-1.0.0`](https://github.com/getnacelle/nacelle-js/tree/ENG-6843/shopify-cart-1.0.0) from the list of branches that `.github/workflows/release.yml` will run on in response to a `push`.
- Updates our GitHub Issues templates to include `packages/shopify-cart` (some other updates were made here...these were quite out-of-date).
- Updates `packages/shopify-cart`'s TypeScript production config to extend the base config. This reduces the number of settings we need to think about and reduces opportunities for configs to become out-of-sync.
- Bumps `@nacelle/shopify-cart` …

build: prepare shopify cart for 1.0.0 publish

---

.changeset/pre.json
.github/workflows/release.yml
packages/storefront-sdk/package-lock.json
packages/storefront-sdk/package.json

Addresses [ENG-8285](https://nacelle.atlassian.net/browse/ENG-8285) - sets up pre-release mode for sdk work 
- Allows us to publish `2.0.0-beta` releases of the storefront sdk as we engage in work. This will allow us to use it in our regression tests.
- A subsequent PR to `main` will configure the `release` action to run on pushes to this branch, similar to what we did for Shopify Cart
1. Run `npm run changeset version` from the repo root
2. Should have a message about being in pre-release mode

chore: enables pre-release mode

---

packages/storefront-sdk/package-lock.json
packages/storefront-sdk/package.json
packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts
packages/storefront-sdk/src/index.test.ts
packages/storefront-sdk/src/index.ts
packages/storefront-sdk/src/utils/errorMessages.ts
packages/storefront-sdk/src/utils/index.ts
packages/storefront-sdk/tsconfig.json
packages/storefront-sdk/vite.config.ts

Addresses [ENG-8318](https://nacelle.atlassian.net/browse/ENG-8318)
> Scaffold the createStorefrontClient function and StorefrontClient class
This PR adds a basic implementation of the `Storefront` client creation function and a `StorefrontClient` class that encapsulates both the public API and private implementation details.
1. Check out the `ENG-8318-storefront-client-scaffolding` branch.
2. Navigate to `packages/storefront-sdk`.
3. `npm run build` - it should create `dist/nacelle-storefront-sdk.js` and `dist/nacelle-storefront-sdk.umd.cjs` without errors.
4. `npm run coverage` - all tests should pass with 100% coverage.

feat: add basic storefront client

---

.changeset/twenty-timers-taste.md
packages/storefront-sdk/.eslintrc.cjs
packages/storefront-sdk/__mocks__/gql/navigation.ts
packages/storefront-sdk/__mocks__/utils/getFetchPayload.ts
packages/storefront-sdk/codegen.yml
packages/storefront-sdk/package-lock.json
packages/storefront-sdk/package.json
packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts
packages/storefront-sdk/src/types/storefront.ts
packages/storefront-sdk/tsconfig.json
packages/storefront-sdk/vite.config.ts

- feat: configure typed-document-node generation
- test: configure vitest typechecking
- test: configure request mocks
- feat: adds v2 query method
- docs: adds changeset for query method changes
Addresses [ENG-8327](https://nacelle.atlassian.net/browse/ENG-8327) - Adds the `.query` method to the v2 of the storefront-sdk. 
1. Adds support for TypedDocumentNodes so we can get typed query responses & users can get typed responses. Updates `codegen` to generate the typed queries from any queries we include in the sdk's `src/graphql/` folder.
2. Initializes the `query` method of the v2 sdk. Note that unlike v1, we return `{data, error}` from the method so that users can handle errors without needing to use `catch`. This is a breaking change between v1 and v2.
3. Adds infrastructure for …

feat: add v2 query method using urql

---

.changeset/sour-rivers-jam.md
packages/storefront-sdk/package-lock.json
packages/storefront-sdk/package.json
packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts
packages/storefront-sdk/src/index.test.ts
packages/storefront-sdk/src/types/after.ts
packages/storefront-sdk/src/utils/constants.ts
packages/storefront-sdk/src/utils/errorMessages.ts
packages/storefront-sdk/src/utils/identity.ts
packages/storefront-sdk/src/utils/index.ts

Addresses [ENG-8320](https://nacelle.atlassian.net/browse/ENG-8320) 
> Implement the after method
This PR implements`@nacelle/storefront-sdk`'s [`.after`](https://docs.nacelle.com/docs/javascript-storefront-sdk#transforming-the-responses-of-sdk-methods) method.
This particular implementation introduces some non-breaking changes.
In `@nacelle/storefront-sdk@1.x`, callbacks registered with the `.after` method were not deletable. This PR changes how callbacks are stored - rather than an array, callbacks are stored in an object that is namespaced by method. If the user provides an optional `callbackId`, we use that as the key. Otherwise, the key takes the form:
```ts
`${methodName}::${n}`
```
where `n` is the current number of callbacks registered to a particular method.
Storing callbacks …

feat: implement the `after` method

---

packages/storefront-sdk/src/client/index.ts

Addresses [ENG-8410](https://nacelle.atlassian.net/browse/ENG-8410) 
Provide helpful TSDoc documentation for the `setConfig` & `getConfig` methods
Adds TSDoc comments to `setConfig` & `getConfig` methods
In `nacelle-js`:
- `git checkout ENG-8410/config-ts-doc`
- `cd packages/storefront-sdk`
- `npm run build && npm link`
In a test project:
- `npm link @nacelle/storefront-sdk`
- Instantiate a client and check if the TSdocs are showing when calling `setConfig` & `getConfig`
[ENG-8410]: https://nacelle.atlassian.net/browse/ENG-8410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: adds TSdocs to `setConfig` and `getConfig`

---

.changeset/chilled-timers-repair.md
.changeset/short-roses-search.md
packages/storefront-sdk-plugins/commerce-queries/__mocks__/gql/content.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/content.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/index.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/queries/content.ts
packages/storefront-sdk-plugins/commerce-queries/src/index.test.ts
packages/storefront-sdk-plugins/commerce-queries/src/index.ts
packages/storefront-sdk-plugins/commerce-queries/src/types/storefront.ts
packages/storefront-sdk-plugins/commerce-queries/src/utils/requestPaginatedData.ts
packages/storefront-sdk-plugins/commerce-queries/vite.config.ts
packages/storefront-sdk-plugins/commerce-queries/vitest.setup.ts
packages/storefront-sdk/src/types/plugins.ts

Addresses [ENG-8321](https://nacelle.atlassian.net/browse/ENG-8321) - adds a content method to the commerce query plugin 
1. Adds a `withConfig` type to the plugin types in the Storefront sdk to enable getting access to the config in plugins
2. Updates `applyAfter` to be protected instead of private so it's more accessible in the plugins
3. Adds the content method to the plugin
4. Adds a fetchPaginatedData method so that other paginated functions can reuse the same logic
1. Navigate to `packages/storefront-sdk` and run `npm run build && npm link`
2. Navigate to `packages/storefront-sdk-plugin/commerce-queries` and run `npm link @nacelle/storefront-sdk`
3. Build with `npm run build` - should build successfully
5. Test with `npm run test` - all tests should pass
6. Typecheck with `npm run …

feat(commerce-queries): add content method 

---

packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts
packages/storefront-sdk/src/index.ts
packages/storefront-sdk/src/types/config.ts

Addresses [ENG-8432](https://nacelle.atlassian.net/browse/ENG-8432) - provides power users the ability to disable APQ requests. 
1. Adds `advancedOptions` key to `StorefrontParams` with `enableApq` key
2. Adds same `advancedOptions` to `setConfig` so users can disable APQ on already initialized storefront
3. Excludes `persistedFetchExchange` from the exchanges array if the new `enableApq` option is false
4. Adds tests for the `enableApq` behavior  
1. Checkout this branch `mdarrik/ENG-8432-add-option-to-disable-apq`
2. Run `npm run build` - build should succeed
3. Run `npm run coverage` - vite typecheck and all tests should pass with 100% coverage
4. (Optional) - use `npm link` with the Storefront SDK. When `enableApq` is false, should see only post requests to the storefront API & when …

feat: add advanced option to control APQ

---

packages/storefront-sdk-plugins/commerce-queries/src/index.test.ts

Addresses [ENG-8659](https://nacelle.atlassian.net/browse/ENG-8659) 
- cleans up the tests to run with APQ disabled. This makes it easier to inspect the args passed to the `fetch` function without needing to send an error response or parse the url. 
1. Checkout this branch
2. Run `npm run coverage` all tests should pass with 100% coverage
[ENG-8659]: https://nacelle.atlassian.net/browse/ENG-8659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(commerce-queries): clean up tests by disabling APQ

---

.changeset/stale-cherries-compare.md
packages/storefront-sdk/__mocks__/utils/getFetchPayload.ts
packages/storefront-sdk/package-lock.json
packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts

Addresses [ENG-8370](https://nacelle.atlassian.net/browse/ENG-8370) 
- Adds the `x-amzn-trace-id` to the `response.error.message` field in the query response. This will allow users to provide info for datadog traces if they need to reach out for support.
1. Checkout this branch `mdarrik/ENG-8370-add-x-amzn-trace-id-to-errors`
3. Run `npm run coverage` - typechecking should pass and test coverage should be 100%
4. Run `npm run build` -  should build successfully
5. Use `npm link` to link to this build of the sdk in a test project. Run an invalid query. The `error.message` field should include `Trace Id: <trace-id>`.
6. (Optional) Use `npm link @nacelle/storefront-sdk` in the `packages/storefront-sdk-plugins/commerce-queries` folder. Then run `npm …

feat: adds trace id to error messages

---

packages/storefront-sdk-plugins/commerce-queries/src/index.test.ts
packages/storefront-sdk-plugins/commerce-queries/src/index.ts

Addresses [ENG-8893](https://nacelle.atlassian.net/browse/ENG-8893) 
> Export types and plugin as named exports
To support TypeScript developers who will be transitioning from version `1.x` to `2.x` of `@nacelle/storefront-sdk`, we should export types associated with the Commerce Queries plugin's methods. We can leave additional Nacelle types up to the developer via GraphQL Codegen (which we will have `2.x` docs for).
1. Exports types used by the Commerce Queries plugin, from the commerce queries plugin.
2. Changes the Commerce Queries plugin from a default export to a named export, to prevent issues related to mixed default & named exports.
1. Check out the `ENG-8893-export-types-and-plugin-as-named-exports` branch.
2. Navigate to `packages/storefront-sdk-plugins/commerce-queries`.
3. …

refactor: prefer named export; export types

---

.changeset/lazy-foxes-fetch.md
packages/storefront-sdk-plugins/commerce-queries/src/index.test.ts
packages/storefront-sdk-plugins/commerce-queries/src/index.ts
packages/storefront-sdk-plugins/commerce-queries/src/types/relay.ts

Fixes [ENG-8882](https://nacelle.atlassian.net/browse/ENG-8882) 
> Commerce queries methods aren't narrowing to a single return type
The `.content`, `.products`, `.productCollections`, and `.productCollectionEntries` methods should be narrowing their return types to a single type, depending on the value of `params.edgesToNodes`.
By narrowing from `Thing[] | ThingEdge[]` to either `Thing[]` or `ThingEdge[]` automatically, we save TypeScript developers from needing to assert the correct type.
- Adds [conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html) to return `Thing[]` when `edgesToNodes` is `true` (which it is, by default) and `ThingEdge[]` when `edgesToNodes` is explicitly set to `false`.
- Updates tests to validate the types when …

fix: use conditional types to avoid assertions

---

.changeset/chilled-timers-repair.md
.changeset/curvy-horses-cheer.md
.changeset/gold-pants-whisper.md
.changeset/lucky-eyes-occur.md
.changeset/mean-weeks-begin.md
.changeset/pre.json
.changeset/silver-dolphins-promise.md
.changeset/swift-snails-appear.md
packages/storefront-sdk-plugins/commerce-queries/CHANGELOG.md
packages/storefront-sdk-plugins/commerce-queries/package-lock.json
packages/storefront-sdk-plugins/commerce-queries/package.json

The original package name (`@nacelle/storefront-sdk-plugin-commerce-queries`) was cumbersome.
- Renames the package from `@nacelle/storefront-sdk-plugin-commerce-queries` to `@nacelle/commerce-queries-plugin`.
- Adjusts changesets and the `.changeset/pre.json` accordingly.
After this PR is merged, we can manually publish `@nacelle/commerce-queries-plugin@1.0.0-beta.0`. This will allow us to publish further `@1.0.0-beta.x` versions using our typical `changesets/action` workflow going forward.

chore: rename commerce queries plugin

---

.github/workflows/release.yml

Our **Release** workflows have been failing in the `ENG-8179/storefront-sdk-2.0` branch. For example: https://github.com/getnacelle/nacelle-js/actions/runs/4257668429/jobs/7408059052
```
nacelle/commerce-queries-plugin: npm ERR! code ETARGET
@nacelle/commerce-queries-plugin: npm ERR! notarget No matching version found for @nacelle/storefront-sdk@^2.0.0-beta.2.
@nacelle/commerce-queries-plugin: npm ERR! notarget In most cases you or one of your dependencies are requesting
@nacelle/commerce-queries-plugin: npm ERR! notarget a package version that doesn't exist.
@nacelle/commerce-queries-plugin: npm ERR! A complete log of this run can be found in:
@nacelle/commerce-queries-plugin: npm ERR!     /home/runner/.npm/_logs/2023-02-23T23_14_47_031Z-debug-0.log
lerna ERR! npm run lockfile:update …
```

build: skip lockfile updates when versioning

---

packages/storefront-sdk/vite.config.ts

Fixes [ENG-8711](https://nacelle.atlassian.net/browse/ENG-8711) 
> Nuxt 2 throws webpack warnings and errors when using the sdk v2 transpiled
The ticket describes a webpack warning in Nuxt 2 projects using `@nacelle/storefront-sdk@1.0.0-beta.1`:
> WARNING in [file] [line]:[column-range]
> Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
When we inspect the Storefront SDK's bundled code, we can find the `new Function("require")` that the warning refers to:
This code is from `@urql/exchange-persisted-fetch`: https://github.com/urql-graphql/urql/blob/34f83b14af9531f0335cd1c9d9fa3bfc8a6835a1/exchanges/persisted-fetch/src/sha256.ts#L19
Recognizing this made it clear that `@urql/exchange-persisted-fetch` was being unexpectedly bundled …

fix: externalize dependencies

---

packages/storefront-sdk-plugins/commerce-queries/package.json
packages/storefront-sdk-plugins/commerce-queries/src/index.test.ts
packages/storefront-sdk-plugins/commerce-queries/src/index.ts
packages/storefront-sdk-plugins/commerce-queries/vite.config.ts

Addresses [ENG-8958](https://nacelle.atlassian.net/browse/ENG-8958)
> Rename export of Commerce Queries plugin
- The Commerce Queries Plugin package name was changed in #337, but the build output filenames weren't changed alongside the package name.
- We wanted to rename the named export for clarity.
1. Renamed the named export from `commerceQueriesPlugin` to `CommerceQueries`.
2. Renames the files generated by the Commerce Query Plugin's `build` script.
1. Check out the `chore/rename-commerce-query-outputs` branch.
3. Navigate to `packages/storefront-sdk-plugins/commerce-queries`.
4. `npm run build`
5. `ls dist/` - all files should be named `nacelle-storefront-sdk-plugin-commerce-queries`.
6. `npm run coverage` - all tests should pass with 100% coverage.
If you want to go the extra mile, …

chore: rename commerce query outputs

---

.changeset/selfish-pumpkins-add.md
packages/storefront-sdk-plugins/commerce-queries/tsconfig.json
packages/storefront-sdk/src/index.ts
packages/storefront-sdk/src/types/config.ts

Addresses [ENG-8957](https://nacelle.atlassian.net/browse/ENG-8957) 
> Remove `compilerOptions.paths` from the Commerce Queries plugin's tsconfig
- Simplifies types
- Exports a type that's needed to support the `WithConfig` type
- Removes the coupling to `@nacelle/storefront-sdk` types via `compilerOptions.paths` in `tsconfig.json`
- Simplifies `tsconfig.json`
1. Check out the `ENG-8957-remove-compileroptions-paths` branch
2. `npm run bootstrap` (as needed)
3. Navigate to `packages/storefront-sdk`
4. `npm run build && npm run coverage` - the package should build and all tests should pass with 100% coverage
5. Navigate to `packages/storefront-sdk-plugins/commerce-queries`
6. `npm run build && npm run coverage` - the package should build and all tests should pass with 100% coverage
If you'd …

fix: export types to decouple packages

---

.changeset/brown-dryers-refuse.md
packages/storefront-sdk/package-lock.json
packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts

Addresses [ENG-9013](https://nacelle.atlassian.net/browse/ENG-9013) 
> Do not send request variables as strings
This PR:
1. Updates the Storefront SDK to ensure that `query` method requests always include `variables` in object form, rather than stringified objects. This circumvents an issue related to APQ and stringified variables.
2. Updates tests to validate (1).
3. Updates the Storefront SDK's lockfile.
1. Check out the `ENG-9013/do-not-send-request-variables-as-strings` branch.
2. Navigate to the `packages/storefront-sdk` directory.
3. `npm run build` - the package should build without errors.
4. `npm run coverage` - all tests should pass with 100% coverage.
When I tested this with a local Vite project (that was set up to test …

fix: do not send request variables as strings

---

.changeset/rotten-monkeys-switch.md
packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts

Fixes [ENG-8179](https://nacelle.atlassian.net/browse/ENG-8179) 
> Storefront SDK doesn't set the `preview` query param when initialized with a `previewToken`
1. Ensures that `preview=true` is set on the `storefrontEndpoint` when the Storefront SDK is initialized with a `previewToken`.
2. Refactors tests for clarity/accuracy.
1. Check out the `ENG-9130/storefront-sdk-preview-query-param` branch.
3. `npm run build` - it should build without errors.
4. `npm run coverage` - it all tests should pass with 100% coverage:
[ENG-8179]: https://nacelle.atlassian.net/browse/ENG-8179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: set preview query param

---

.changeset/silent-meals-push.md
packages/storefront-sdk/src/client/createClient.test.ts
packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts
packages/storefront-sdk/src/utils/constants.ts
packages/storefront-sdk/src/utils/index.ts

Addresses [ENG-9141](https://nacelle.atlassian.net/browse/ENG-9141) 
> Storefront SDK uses wrong header name for preview token
#309 introduced a bug: instead of the preview token being set as [`x-nacelle-preview-token`](https://docs.nacelle.com/docs/preview-data#storefront-api), it was incorrectly set as `x-nacelle-space-token`.
- Uses the correct header name to convey a Nacelle Preview Token to the Nacelle Storefront GraphQL API
- Refactors unit tests related to preview mode
- Request headers are now tested for the correct header name and value
- Removes a redundant test in `packages/storefront-sdk/src/client/createClient.test.ts`
1. Check out the `ENG-9141/fix-preview-token-header-name` branch
3. `npm run build` - the package should build without …

fix: preview token header

---

.github/workflows/release.yml

@NWRichmond following your details outlined [here](https://nacelle.atlassian.net/browse/ENG-8930), the release workflow has been updated to:
- run `lerna run --parallel lockfile:update`
- commit the changes back to the existing `ref` branch using the github actions bot user.
- push the changes back to the `ref` target

chore(ENG-8934): update package-lock files after publish

---

.changeset/modern-pillows-peel.md
packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts
packages/storefront-sdk/src/index.test.ts
packages/storefront-sdk/src/index.ts
packages/storefront-sdk/src/types/config.ts

Addresses [ENG-8872](https://nacelle.atlassian.net/browse/ENG-8872) 
> Allow developers to supply urql exchanges via an `exchanges` parameter
This PR allows Storefront SDK users to supply [`exchanges`](https://formidable.com/open-source/urql/docs/architecture/#the-client-and-exchanges) in the `StorefrontClientParams`.
1. Check out the `ENG-8872/exchanges-param` branch
2. Navigate to the `packages/storefront-sdk` directory
3. `npm run build` - the package should build without errors
4. `npm run coverage` - all tests should pass with 100% coverage
[ENG-8872]: https://nacelle.atlassian.net/browse/ENG-8872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: accept `exchanges` in initialization params

---

.changeset/silver-shirts-tan.md
.changeset/twelve-rivers-bathe.md
packages/storefront-sdk-plugins/commerce-queries/package-lock.json
packages/storefront-sdk-plugins/commerce-queries/package.json
packages/storefront-sdk-plugins/commerce-queries/src/index.test.ts
packages/storefront-sdk/package-lock.json
packages/storefront-sdk/package.json
packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts
packages/storefront-sdk/src/index.test.ts
packages/storefront-sdk/src/index.ts

Addresses [ENG-9479](https://nacelle.atlassian.net/browse/ENG-9479) 
> Upgrade SDK and Commerce Queries plugin to urql v4
This PR upgrades `@nacelle/storefront-sdk` to use [`@urql/core`](https://www.npmjs.com/package/@urql/core) version 4. Guided by the [`@urql/core` changelog](https://github.com/urql-graphql/urql/blob/main/packages/core/CHANGELOG.md#400), this PR removes the dependency on [`graphql`](https://www.npmjs.com/package/graphql) and updates the urql exchanges that we're using in the Storefront SDK.
This PR also updates `@nacelle/commerce-queries-plugin` to depend on Storefront SDK version [`2.0.0-beta.9`](https://www.npmjs.com/package/@nacelle/storefront-sdk/v/2.0.0-beta.9) or higher for local dev, which allows us to use the new `exchanges` param in unit tests. We can also …

feat: upgrade internals to `@urql/core@4`

---

.changeset/nine-taxis-fetch.md
packages/storefront-sdk/src/client/index.ts
packages/storefront-sdk/src/index.ts

Addresses [ENG-9169](https://nacelle.atlassian.net/browse/ENG-9169) 
To correct an issue with types that prevented the commerce query plugin from building when installing the SDK rather than using symlinking
- Replaces `AnyVariables` in the Storefront SDK's query method with an inline type: `Record<string, unknown> | undefined`
- `npm run build`
- copy the `dist` folder
- navigate to `node_modules/@nacelle/storefront-sdk`
- delete the `dist` folder and replace it with the one from the current SDK build
[ENG-9169]: https://nacelle.atlassian.net/browse/ENG-9169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: install sdk in commerce query type issue

---

packages/storefront-sdk-plugins/commerce-queries/package-lock.json
packages/storefront-sdk-plugins/commerce-queries/package.json

This PR updates `@nacelle/commerce-queries-plugin` to depend on `>=2.0.0-beta.10` of `@nacelle/storefront-sdk`. This encompasses `2.0.0`.

chore: configure Storefront SDK dependency version

---

packages/storefront-sdk-plugins/commerce-queries/package-lock.json
packages/storefront-sdk-plugins/commerce-queries/package.json

This PR upgrades the Commerce Queries plugin's devDep on `@nacelle/storefront-sdk` to overcome the **Release** issues here: https://github.com/getnacelle/nacelle-js/actions/runs/4822309441/jobs/8589361575

fix: upgrade devDep

---

.github/workflows/release.yml

This PR temporarily disables lockfile updates in the **Release** script to overcome issues with https://github.com/getnacelle/nacelle-js/actions/runs/4822366925/jobs/8589502929

build: skip lockfile updates

---

.changeset/kind-frogs-chew.md
packages/storefront-sdk/src/client/createClient.test.ts
packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts
packages/storefront-sdk/src/utils/constants.ts

Addresses [ENG-9576](https://nacelle.atlassian.net/browse/ENG-9576) 
> Send package version in 'x-nacelle-sdk-version' header
1. Adds an `x-nacelle-sdk-version` header to requests. This matches `@nacelle/storefront-sdk@1.x` behavior.
2. Moves the handling of endpoint query params and headers to new static methods. This allows us to simplify the constructor and the `setConfig` method.
1. Check out the `ENG-9576/send-package-version-in-x-nacelle-sdk-version-header` branch
3. `npm run build` - the package should build without errors
4. `npm run coverage` - all test should pass with 100% coverage
[ENG-9576]: https://nacelle.atlassian.net/browse/ENG-9576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: request headers include `x-nacelle-sdk-version`

---

.changeset/mighty-balloons-cry.md
packages/storefront-sdk/vite.config.ts

Addresses [ENG-9911](https://nacelle.atlassian.net/browse/ENG-9911) 
> Storefront SDK is bundling the persisted fetch exchange
This bug is a consequence of negligence in #370. The name of the Persisted Fetch Exchange package changed with urql 4, but I forgot to update that package's name in `packages/storefront-sdk/vite.config.ts`.
This PR updates `packages/storefront-sdk/vite.config.ts` to correctly exclude the Persisted Fetch Exchange from the bundle. It also removes `graphql` from the Vite config, because `graphql` is no longer a dependency (as of #370).
1. Check out the `ENG-9911/externalize-deps` branch
3. `npm run build` - there should be no build errors
4. `npm run coverage` - all tests should pass with 100% coverage
5. Clone the …

fix: externalize deps

---

.github/workflows/release.yml

Addresses [ENG-8894](https://nacelle.atlassian.net/browse/ENG-8894) 
The `changelog` automation didn't trigger during last release indicating that the `steps.changes.outputs.storefront-sdk` wasn't being set to `true`
- Adds the `storefront-sdk` to the `changes` step in the github `release` workflow
[ENG-8894]: https://nacelle.atlassian.net/browse/ENG-8894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add sdk to github workflow `changes`

---

packages/shopify-cart/src/client/client-dom.spec.ts
packages/shopify-cart/src/client/index.ts

Addresses [ENG-9772](https://nacelle.atlassian.net/browse/ENG-9772) 
Missing parameters to `shopify-cart` package resulted in unclear errors
- Adds a descriptive error when `shopifyShopId` or `shopifyStorefrontAccessToken` are missing
In `packages/shopify-cart`:
- `npm i && npm run build`
- copy the resulting `dist` folder
In `reference-stores/nuxt`
- Find `node_modules/@nacelle/shopify-cart` directory, remove the `dist` folder and replace it with the previously copied one
- Don't provide `SHOPIFY_SHOP_ID` or `SHOPIFY_STOREFRONT_ACCESS_TOKEN` `env` vars
[ENG-9772]: https://nacelle.atlassian.net/browse/ENG-9772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add errors to missing env vars

---

.changeset/eighty-singers-do.md
packages/storefront-sdk-plugins/commerce-queries/__mocks__/gql/content.ts
packages/storefront-sdk-plugins/commerce-queries/__mocks__/gql/product.ts
packages/storefront-sdk-plugins/commerce-queries/__mocks__/gql/productCollectionEntries.ts
packages/storefront-sdk-plugins/commerce-queries/__mocks__/gql/productCollections.ts
packages/storefront-sdk-plugins/commerce-queries/package-lock.json
packages/storefront-sdk-plugins/commerce-queries/package.json
packages/storefront-sdk-plugins/commerce-queries/src/graphql/documents.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/collection.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/collectionContent.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/content.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/product.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/productContent.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/variant.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/variantContent.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/queries/content.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/queries/productCollectionEntries.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/queries/productCollections.ts
packages/storefront-sdk-plugins/commerce-queries/src/index.test.ts
packages/storefront-sdk-plugins/commerce-queries/src/types/storefront.ts

Addresses [ENG-9068](https://nacelle.atlassian.net/browse/ENG-9068) 
Add `__typename` to fragments
In the Commerce Queries folder `packages/storefront-sdk-plugins/commerce-queries`:
- `npm run test`
When running Codegen some strange things happened to the following files:
- packages/storefront-sdk-plugins/commerce-queries/src/graphql/documents.ts
- packages/storefront-sdk-plugins/commerce-queries/src/types/storefront.ts
With the inclusion of `Pricing` and `Money` types, let's discuss wether or not we want to include this in this PR
[ENG-9068]: https://nacelle.atlassian.net/browse/ENG-9068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: typename in commerce-queries plugin

---

.changeset/angry-apricots-jog.md
packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts

Addresses [ENG-10894](https://nacelle.atlassian.net/browse/ENG-10894) 
> SDK should retry on network errors
The Storefront SDK wasn't retrying on certain network errors like `ETIMEDOUT`.
This PR updates the default [urql request retry](https://formidable.com/open-source/urql/docs/advanced/retry-operations) configuration so that retries happen in response to any network error. Previously, retries only happened in response to certain HTTP error statuses. This made it difficult to respond to transient network issues like `ETIMEDOUT`.
This PR also adds a couple of new unit tests to achieve 100% coverage.
This is a tough PR to test end-to-end. Instead of asking reviewers to follow steps, I'll provide my own testing results.
In a fresh project, I used [`nock`](https://github.com/nock/nock) to …

fix: retry on all network errors

---

.github/workflows/pr.yml
.github/workflows/release.yml
packages/storefront-sdk-plugins/commerce-queries/package-lock.json
packages/storefront-sdk-plugins/commerce-queries/package.json

Addresses [ENG-11299](https://nacelle.atlassian.net/browse/ENG-11299) 
> Cache nacelle-js package dependencies in workflows
This PR updates the `setup-node` action to version 4, which supports [dependency caching](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows). It also adds the necessary config settings (`cache` and `cache-dependency-path`).
Docs related to this change:
- https://github.com/actions/setup-node#caching-global-packages-data
- https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data (see **Using wildcard patterns to cache dependencies**)
In `@nacelle/commerce-queries-plugin`'s `package.json`, the dependency version operator (both peerDep and devDep) for `@nacelle/storefront-sdk` has been …

feat: cache installed dependencies
