packages/shopify-checkout/README.md
packages/shopify-checkout/__tests__/mocks/index.ts
packages/shopify-checkout/package-lock.json
packages/shopify-checkout/src/checkout-client.types.ts
packages/shopify-checkout/src/client/actions/findCheckout.spec.ts
packages/shopify-checkout/src/client/actions/findCheckout.ts
packages/shopify-checkout/src/client/client-dom.spec.ts
packages/shopify-checkout/src/client/index.ts
packages/shopify-checkout/src/graphql/fragments/index.ts
packages/shopify-checkout/src/graphql/mutations/index.ts
packages/shopify-checkout/src/graphql/queries/index.ts
packages/shopify-checkout/src/utils/buildCheckout.spec.ts
packages/shopify-checkout/src/utils/buildCheckout.ts
packages/shopify-checkout/src/utils/createGqlClient.ts

Addresses [LS-1658](https://nacelle.atlassian.net/browse/LS-1548)
> Implement lineItems & discountApplications fragments in mutations and queries
This PR brings changes from #83 & #84 into `main`.
- Check out the `LS-1546/line-item-discounts` branch
- `cd packages/shopify-checkout`
- `npm run build` - the build process should complete without errors.
- `npm run test:ci` - all unit tests should pass.

feat(shopify-checkout): checkout line items

---

examples/flash-sale/README.md

Adds upon [[LS-1560](https://nacelle.atlassian.net/browse/LS-1560)] 
- Adds a link to the README to a CodeSandbox running the code.
**Note**: This is my first time setting up a CodeSandbox, so let me know if there are any changes needed.

chore(flash-sale): add codesandbox to readme

---

reference-stores/next/components/Search/SearchAutocomplete.js

Fixes overflow issue on autocomplete drawer for tablets.
Addresses a PR request [here](https://github.com/getnacelle/nacelle-js/pull/133#discussion_r868424686) that came it after approval/merge

chore: fix search autocomplete overflow

---

packages/shopify-checkout/package-lock.json
packages/shopify-checkout/src/client/actions/applyDiscount.ts
packages/shopify-checkout/src/client/actions/removeDiscount.ts
packages/shopify-checkout/src/client/client-dom.spec.ts

Fixes [[ENG-5836](https://nacelle.atlassian.net/browse/ENG-5836)] 
- Apply discount and remove discounts were passing an input param which isn't used by the Shopify API
- Fix testing
- `git checkout ENG-5836--fix-checkout-graphql`
- `cd packages/shopify-checkout/`
- `npm run test`
A good way to test it locally for me was to do the following
- In this branch `npm run build && npm link`
- In another folder make a new React App
- - `npx create-react-app discount-app`
- - Replace the `src` files with the files from @NWRichmond's [discount testing app](https://codesandbox.io/s/cocky-nightingale-xi80sg)
- - `npm i @nacelle/react-hooks && npm i @nacelle/shopify-checkout`
- - `npm link @nacelle/shopify-checkout`
- - `npm run start`
- - Applying/Removing discount should work as expected, without …

fix: apply/remove discount params

---

examples/svelte/package.json
package.json

Fixes [[ENG-6318](https://nacelle.atlassian.net/browse/ENG-6318)]
Ensures lerna does not build private packages/projects

chore: lerna build --no-private

---

.changeset/config.json
package-lock.json
package.json

Fixes [ENG-6342](https://nacelle.atlassian.net/browse/ENG-6342) 
- Scaffolds changesets
The only option that was adjusted within changesets `config.json` was to flip `"access": "public"`.  Seems like the recommended setting for public repos.  I'm not sure that we need to update any of the other default settings.  Open to feedback.

chore: scaffold changesets

---

.github/workflows/release.yml
package.json

Fixes [[ENG-6343](https://nacelle.atlassian.net/browse/ENG-6343)] 
Add changesets actions and scripts
Tricky to test for the moment as only pushes on the main branch will trigger the action

feat: setup changesets action

---

packages/gatsby-source-nacelle/CHANGELOG.md
packages/sanity-plugin-nacelle-input/CHANGELOG.md
packages/shopify-checkout/CHANGELOG.md
packages/vue/CHANGELOG.md

Fixes [[ENG-6346](https://nacelle.atlassian.net/browse/ENG-6346)] 
- retroactively add changelogs for packages

chore: retroactively add changelogs

---

CONTRIBUTING.md

Fixes [[ENG-6345](https://nacelle.atlassian.net/browse/ENG-6345)] 
Adds changesets docs to CONTRIBUTING.md

feat: changesets docs

---

.changeset/config.json
.github/workflows/release.yml
CONTRIBUTING.md
package-lock.json
package.json
packages/gatsby-source-nacelle/CHANGELOG.md
packages/sanity-plugin-nacelle-input/CHANGELOG.md
packages/shopify-checkout/CHANGELOG.md
packages/vue/CHANGELOG.md

Fixes [[ENG-6445](https://nacelle.atlassian.net/browse/ENG-6445)] 
Implements changesets versioning

feat: changesets

---

.github/workflows/release.yml
package.json

[ENG-6820](https://nacelle.atlassian.net/browse/ENG-6820) 
- Updates release workflow, and adds postinstall bootstrap
- If release workflow succeeds we should be good
_I don't think we need a changeset for this PR since no packages should get bumped?_

chore: workflow + scripts

---

.changeset/gorgeous-gifts-sip.md
packages/shopify-cart/README.md

Addresses [ENG-6853](https://nacelle.atlassian.net/browse/ENG-6853)
> Adds versioning/release schedule to docs

docs: support/release schedule

---

packages/shopify-cart/src/graphql/fragments/cart.ts
packages/shopify-cart/src/graphql/fragments/discountAllocation.ts

Addresses [ENG-6899](https://nacelle.atlassian.net/browse/ENG-6899)
> Adds `discountAllocation fragment`

chore: add discountAllocation fragment

---

packages/shopify-cart/package.json

Fixes [[ENG-7092](https://nacelle.atlassian.net/browse/ENG-7092)] 
- node v18 check
- update node maximum version
Tests:
Build:
e2e:

chore: node v18 check

---

packages/shopify-cart/README.md

Fixes [[ENG-7061](https://nacelle.atlassian.net/browse/ENG-7061)] 
- Removes no longer applicatble language from `shopify-cart` `README.md`

chore: remove non applicable readme language

---

packages/shopify-cart/README.md

Fixes [[ENG-7056](https://nacelle.atlassian.net/browse/ENG-7056)] 
- Document TS types access in README

chore: document type access in readme

---

packages/shopify-cart/README.md

This PR formats the `packages/shopify-cart/README.md` for the sake of triggering `.github/workflows/release.yml`.

docs: formatting

---

.changeset/strange-lemons-pay.md
packages/shopify-cart/src/client/actions/cartAttributesUpdate.ts
packages/shopify-cart/src/client/actions/cartBuyerIdentityUpdate.ts
packages/shopify-cart/src/client/actions/cartCreate.ts
packages/shopify-cart/src/client/actions/cartDiscountCodesUpdate.ts
packages/shopify-cart/src/client/actions/cartLinesAdd.ts
packages/shopify-cart/src/client/actions/cartLinesRemove.ts
packages/shopify-cart/src/client/actions/cartLinesUpdate.ts
packages/shopify-cart/src/client/actions/cartNoteUpdate.ts

Addresses [ENG-7136](https://nacelle.atlassian.net/browse/ENG-7136)
> Check existense of parent key before accessing child.  This was causing js errors to be returned instead of Shopify cart/error responses.
- `git checkout ENG-7136/validate-shopify-errors`
- `npm run test:ci`

fix: validate cart responses exist

---

packages/shopify-cart/package.json

Fixes [[ENG-7315](https://nacelle.atlassian.net/browse/ENG-7315)] 
Add `lockfile:update` script to `shopify-cart` in preparation to merge
Meant to go along following [PR](https://github.com/getnacelle/nacelle-js/pull/272)

chore: add lockfile command to shopify-cart

---

.changeset/young-scissors-wash.md
packages/storefront-sdk/package-lock.json
packages/storefront-sdk/package.json
packages/storefront-sdk/src/client/createClient.test.ts
packages/storefront-sdk/src/client/index.test.ts
packages/storefront-sdk/src/client/index.ts
packages/storefront-sdk/vite.config.ts
packages/storefront-sdk/vitest.setup.ts

- adds retry exchange
- adds persisted fetch exchange for APQ
Addresses [ENG-8314](https://nacelle.atlassian.net/browse/ENG-8314) - configures urql exchanges for retry and persisted queries. 
1. Adds urql's `retryExchange` and `persistedFetchExchange` to handle retrying requests and persisted queries
2. Adds logic to retry fetching for certain status codes and graphql errors to match v1's retry logic.
3. Adds test for retry logic. Note that this test is the slowest, but even when switched to use `each` takes a similar amount of time
1. Run `npm run bootstrap` from the root of the repo to install new dependencies
2. Run `npm run test` all tests should pass
3. If you make a request to `hf` using this branch, it should make a `get` request using a persisted query.
[ENG-8314]: …

feat: configure urql exchanges

---

packages/storefront-sdk/src/client/index.ts

Addresses [ENG-8409](https://nacelle.atlassian.net/browse/ENG-8409) - improves documentation of the v2 sdk's query method 
1. Adds js-doc comments to the sdk's query method.
2. Adds js-doc comments to the sdk's StorefrontResponse type.
1. Use `npm run build` && `npm link` to import the sdk into another project. (Can also use the same file in this project)
2. Instantiate an sdk client
3. Review the in-editor information for the `client.query` method & the different fields returned in the response.  
[ENG-8409]: https://nacelle.atlassian.net/browse/ENG-8409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: add js docs to the query method and StorefrontResponse type

---

.changeset/lovely-bugs-enjoy.md
packages/shopify-cart/README.md
packages/shopify-cart/__tests__/mocks/index.ts
packages/shopify-cart/codegen.yml
packages/shopify-cart/docs/custom-fragments.md
packages/shopify-cart/package-lock.json
packages/shopify-cart/src/types/shopify.type.ts
packages/shopify-cart/src/utils/createGqlClient.ts

Addresses [ENG-8375](https://nacelle.atlassian.net/browse/ENG-8375) 
> Upgrade Shopify Cart package to use 2023-01 Shopify Storefront API
This PR upgrades `@nacelle/shopify-cart`'s Shopify Storefront API version from `2022-10` to `2023-01`, which is now the latest stable API version.
1. Check out the `ENG-8375-shopify-storefront-api-version-2023-01` branch.
2. Navigate to `packages/shopify-cart`.
3. `npm run build` - there should be no errors.
4. `npm run test:ci` - all tests should pass with 100% coverage.
5. `npm run codegen` - there should be no uncommitted changes.
In local testing, I found that the Next.js Reference Store made requests with the `2023-01` API version, and all cart CRUD actions worked as expected:
https://user-images.githubusercontent.com/5732000/212422927-c5f84d5e-9b27 …

feat: upgrade to latest Shopify Storefront API

---

.changeset/silver-dolphins-promise.md
packages/storefront-sdk-plugins/commerce-queries/src/index.test.ts
packages/storefront-sdk-plugins/commerce-queries/src/index.ts

Addresses [ENG-8323](https://nacelle.atlassian.net/browse/ENG-8323) 
- Add the `navigation` method to the commerce queries plugin
- On the monorepo root `npm run bootstrap`
- Navigate to `packages/storefront-sdk-plugins/commerce-queries` 
- `npm run test` every test should pass
- In the plugin directory
- - `npm run build`
- In a local project `package.json` dependencies, add the local path to the `commerce-queries` plugin
```
"@nacelle/storefront-sdk-plugin-commerce-queries": "file: LOCAL_PATH"
```
- - `npm install`
- - In a JS/TS file, add the following code:
```js
import {StorefrontClient} from '@nacelle/storefront-sdk'
import commerceQueriesPlugin from '@nacelle/storefront-sdk-plugin-commerce-queries'
const storefrontEndpoint = …
```

feat: add `navigation` method

---

.changeset/curvy-horses-cheer.md
packages/storefront-sdk-plugins/commerce-queries/__mocks__/gql/product.ts
packages/storefront-sdk-plugins/commerce-queries/codegen.yml
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/index.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/media.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/metafield.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/product.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/productContent.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/productOption.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/productPriceBreak.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/productPriceRule.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/seo.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/variant.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/variantContent.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/queries/index.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/queries/products.ts
packages/storefront-sdk-plugins/commerce-queries/src/index.test.ts
packages/storefront-sdk-plugins/commerce-queries/src/index.ts
packages/storefront-sdk-plugins/commerce-queries/src/types/storefront.ts
packages/storefront-sdk-plugins/commerce-queries/src/utils/requestPaginatedData.ts

Addresses [ENG-8324](https://nacelle.atlassian.net/browse/ENG-8324) 
1. Creates the product query and a number of fragments
2. Updates `codegen.yaml` to have `dedupeFragments: true` so that the query is generated with a single fragment
3. Adds the products method and associated tests
1. Checkout this branch `mdarrik/ENG-8324-add-product-method`
2. Run `npm coverage` typechecking and all tests should succeed
3. Run `npm run build` should build successfully
4. Create an instance of the sdk with the CommerceQueries plugin and use the `sdk.products()` method - should fetch successfully
[ENG-8324]: https://nacelle.atlassian.net/browse/ENG-8324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(commerce-queries): add product method

---

.changeset/mean-weeks-begin.md
packages/storefront-sdk-plugins/commerce-queries/__mocks__/gql/productCollections.ts
packages/storefront-sdk-plugins/commerce-queries/codegen.yml
packages/storefront-sdk-plugins/commerce-queries/package.json
packages/storefront-sdk-plugins/commerce-queries/src/graphql/documents.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/collectionContent.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/fragments/index.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/queries/index.ts
packages/storefront-sdk-plugins/commerce-queries/src/graphql/queries/productCollections.ts
packages/storefront-sdk-plugins/commerce-queries/src/index.test.ts
packages/storefront-sdk-plugins/commerce-queries/src/index.ts
packages/storefront-sdk-plugins/commerce-queries/src/types/storefront.ts
packages/storefront-sdk-plugins/commerce-queries/src/utils/constants.ts
packages/storefront-sdk-plugins/commerce-queries/src/utils/messages.ts
packages/storefront-sdk-plugins/commerce-queries/src/utils/requestPaginatedData.ts
packages/storefront-sdk-plugins/commerce-queries/vite.config.ts

Addresses [ENG-8325](https://nacelle.atlassian.net/browse/ENG-8325) 
> Implement the `productCollections` method
1. Adds the `productCollections` method to `@nacelle/storefront-sdk-plugin-commerce-queries` to match `@nacelle/storefront-sdk@1.x`'s `productCollections` method.
2. Refactors some `console` side effects in other methods with new utilities.
3. Refactors some tests to simplify and improve clarity.
1. Check out the `ENG-8325-implement-the-productcollections-method` branch.
2. Navigate to `packages/storefront-sdk-plugins/commerce-queries`.
4. `npm run coverage` - all tests should pass with 100% coverage.
5. `npm run build` - there should be no build errors.
From there, you can test in a local project via `npm link`. In my local testing, I found that the `productCollections` method …

feat: implement the `productCollections` method

---

.changeset/pre.json
packages/storefront-sdk-plugins/commerce-queries/CHANGELOG.md
packages/storefront-sdk-plugins/commerce-queries/package.json
packages/storefront-sdk/CHANGELOG.md
packages/storefront-sdk/package.json

Versions packages for a new beta release of the sdk.

chore: version packages

---

.changeset/lucky-eyes-occur.md
packages/storefront-sdk-plugins/commerce-queries/src/index.test.ts
packages/storefront-sdk-plugins/commerce-queries/src/index.ts
packages/storefront-sdk-plugins/commerce-queries/src/utils/handle-errors.test.ts
packages/storefront-sdk-plugins/commerce-queries/src/utils/handle-errors.ts
packages/storefront-sdk-plugins/commerce-queries/src/utils/requestPaginatedData.ts
packages/storefront-sdk-plugins/commerce-queries/test/utils/handle-errors.test.ts

Addresses [ENG-8502](https://nacelle.atlassian.net/browse/ENG-8502) 
Adds error handling to the commerce queries plugin
Modifies the shape of the returned object to be the direct data instead of `{data, error}`
- `git checkout ENG-8502/error-handling-plugin`
- Run `npm run coverage` all tests should pass with 100% coverage
[ENG-8502]: https://nacelle.atlassian.net/browse/ENG-8502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: error handling

---

packages/storefront-sdk/vite.config.ts

Addresses [ENG-8581](https://nacelle.atlassian.net/browse/ENG-8581) 
Externalizes `@urql/core` and `graphql` dependencies so they aren't included in the final bundle. This allows users to use these dependencies without increasing their bundle size. 
- Checkout this branch `mdarrik/ENG-8581-externalize-sdk-deps`
- Run `npm run build` - this should build correctly
- Use `npm link` or install the `@nacelle/storefront-sdk@beta` and  replace the `node_modules/@nacelle/storefront-sdk/dist` folder with the built dist folder. In both cases, the sdk should be useable from a bundler/site build
[ENG-8581]: https://nacelle.atlassian.net/browse/ENG-8581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(storefront-sdk): externalzie `@urql/core` and `graphql` deps

---

packages/storefront-sdk-plugins/commerce-queries/src/utils/handle-errors.test.ts
packages/storefront-sdk-plugins/commerce-queries/src/utils/handle-errors.ts

Addresses [ENG-8823](https://nacelle.atlassian.net/browse/ENG-8823) 
- Update the Commerce Queries plugin to just throw the error.message instead of handling different error types
- Remove complexit error test
[ENG-8823]: https://nacelle.atlassian.net/browse/ENG-8823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove `complexity error` error handling

---

.changeset/early-pigs-move.md
packages/storefront-sdk/src/client/index.ts
packages/storefront-sdk/src/index.test.ts
packages/storefront-sdk/src/index.ts

Addresses [ENG-8871](https://nacelle.atlassian.net/browse/ENG-8871) 
The storefront method export is unnecessary since creating a new `StorefrontClient` instance does the same thing.
- `npm run test` should pass
-  Locally, the storefront method shouldn't be importable.
[ENG-8871]: https://nacelle.atlassian.net/browse/ENG-8871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove storefront method

---

packages/storefront-sdk/src/index.ts

Addresses [ENG-8881](https://nacelle.atlassian.net/browse/ENG-8881) - fixes `query` types when using plugins 
1. Exports the `QueryParams` type from the `storefront-sdk` repo.
2. Moves the `StorefrontResponse` export to an `export type` statement for clarity
1. Checkout this branch `mdarrik/ENG-8881-fix-commerce-queries-query-type`
2. Run `npm run coverage` in the `packages/storefront-sdk` folder -  all tests should pass and the `vite` typechecking should complete successfully
3. Run `npm build` should build successfully and tsc should complete. 
4. Use `npm link` to connect the  `@nacelle/storefront-sdk` and `@nacelle/commerce-queries-plugin` to a TS project that has a `typedDocumentNode` configured (can look at CommerceQueries as an example in how to create them)
5. Create an instance …

chore: exports QueryParams type

---

reference-stores/next/components/Collection/CollectionGrid.js
reference-stores/next/components/Layout/Layout.js
reference-stores/next/components/Newsletter/Newsletter.js
reference-stores/next/package-lock.json
reference-stores/next/package.json
reference-stores/next/pages/_app.js
reference-stores/next/pages/collections/[handle].js
reference-stores/next/pages/index.js
reference-stores/next/pages/pages/[handle].js
reference-stores/next/pages/products/[handle].js
reference-stores/next/pages/search.js
reference-stores/next/services/nacelleClient.js
reference-stores/next/utils/resolvers/resolveFeaturedProducts.js
reference-stores/next/utils/resolvers/resolveSiteData.js

Addresses [ENG-8503](https://nacelle.atlassian.net/browse/ENG-8503) 
- Update the Next reference store to make use of the SDK v2
- `npm run build && npm run start` 
- Explore website
[ENG-8503]: https://nacelle.atlassian.net/browse/ENG-8503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: use SDK v2

---

.changeset/itchy-suns-travel.md
packages/storefront-sdk-plugins/commerce-queries/README.md
packages/storefront-sdk/README.md
packages/storefront-sdk/package-lock.json
packages/storefront-sdk/package.json

Addresses [ENG-8917](https://nacelle.atlassian.net/browse/ENG-8917) 
> Scaffold READMEs with links to docs site pages
1. Visit [the Storefront SDK README](https://github.com/getnacelle/nacelle-js/tree/ENG-8917/storefront-sdk-readmes/packages/storefront-sdk#nacelle-storefront-sdk) and check that links go to the expected places.
2. Visit [the Commerce Queries Plugin README](https://github.com/getnacelle/nacelle-js/tree/ENG-8917/storefront-sdk-readmes/packages/storefront-sdk-plugins/commerce-queries#nacelle-commerce-queries-plugin) and check that links go to the expected places.
[ENG-8917]: https://nacelle.atlassian.net/browse/ENG-8917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: scaffold READMEs

---

packages/storefront-sdk/package-lock.json

This PR addresses lockfile issues that led to failures in https://github.com/getnacelle/nacelle-js/actions/runs/4813448668

chore: update lockfile

---

packages/gatsby-source-nacelle/README.md
packages/vue/README.md

Supports [ENG-9953](https://nacelle.atlassian.net/browse/ENG-9953) 
> Deprecate dead-weight packages
This PR updates READMEs of deprecated packages, just in case the npm deprecations aren't noticed.
[ENG-9953]: https://nacelle.atlassian.net/browse/ENG-9953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: add deprecation message to READMEs

---

examples/shopify-accounts/package-lock.json
examples/shopify-accounts/package.json
packages/storefront-sdk-plugins/commerce-queries/package-lock.json
packages/storefront-sdk/package-lock.json

Addresses [ENG-11205](https://nacelle.atlassian.net/browse/ENG-11205) 
> Ensure that `nacelle-js` monorepo dependencies can be installed and bootstrapped
This PR fixes dependencies in `examples/shopify-accounts` so that packages can be bootstrapped at the monorepo root.
It also updates Storefront SDK / Commerce Queries Plugin lockfiles.
1. Check out the `ENG-11205/fix-monorepo-dependencies` branch
2. `npm i && npm run bootstrap` - there should be no errors when installing or bootstrapping, and there should be no uncommitted changes
[ENG-11205]: https://nacelle.atlassian.net/browse/ENG-11205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: broken dependencies
